# Generated by Django 6.0.4 on 2026-04-15 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус')),
                ('total_likes', models.IntegerField(default=0, verbose_name='Всего лайков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.video', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Файл')),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('FHD', 'FHD'), ('UHD', 'UHD')], default='HD', max_length=10, verbose_name='Качество')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.video', verbose_name='Видео')),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['owner', 'is_published'], name='api_video_owner_i_02cc00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('video', 'user')},
        ),
    ]
